### ISSUE TITLE
Авторизация/Быстрая регистрация

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#100]
На странице Оформление заказа/Оформление бронирования есть блок авторизации/регистрации пользователя.
Сейчас переключение между формами осуществляется по нажатию на "Авторизоваться/Быстрая регистрация"

Судя по ТЗ должно быть две кнопочки "Вход" и "Регистрация". Если отметка стоит в поле Вход, то предоставляется форма авторизации, если в поле Регистрация - форма быстрой регистрации

Строку "Вход через: ..." нужно опустить вниз, после всех полей форм

**Comment by o-bender** [comment]
> Строку "Вход через: ..." нужно опустить вниз, после всех полей форм

Не получится

**Comment by Svetlana12** [comment]
я так понимаю, что должно быть сразу две кнопочки видно (радиокнопки)

**Comment by o-bender** [comment]
Будем считать, что я туповат и не понял этого. Ну и... ты правда можешь придумать способ сунуть туда пару radiobutton??

**Comment by Svetlana12** [comment]
В форме авторизации поле "Логин" нужно переименовать в "Электронная почта"

Еще ЛН предлагает добавить после пароля кнопку "Вход"

**Comment by o-bender** [comment]
Кнопку?)) Ладно, он видимо просто ещё не понял, как всё это работает. После последних правок. Думаю поймёт.
