### ISSUE TITLE
Мои бронирования

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#102]
Сейчас в окне "Изменение данных туриста" поле "Серия и номер паспорта" - не обязательно для заполнения (нет звездочки). Но все равно без этого поля Счет нельзя получить  - выдается сообщение "Необходимо полностью заполнить данные о туристах".

**Comment by Svetlana12** [comment]
Сейчас, если нажать Получить счет открывается новая страница с ошибкой.

**Comment by Svetlana12** [comment]
Если выбрать Оплатить картой - выдается сообщение, что нужно заполнить все данные, при этом, если нажать значок редактирования путевки, ничего не происходит, окно изменения данных туриста не открывается

**Comment by o-bender** [comment]
А сейчас?

**Comment by Svetlana12** [comment]
все так же

**Comment by o-bender** [comment]
А сейчас?

**Comment by Svetlana12** [comment]
счет выводится, изменять путевку можно, а оплата картой также - не заполнены данные
