### ISSUE TITLE
обновить год

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga3.1#104]
Предлагаю в письмах с подтверждением бронирования и принятия заявки, в письме  с отменой бронирования обновить число года после знака копирайта.
![default](https://user-images.githubusercontent.com/38527203/44906635-25d2db80-ad1e-11e8-9374-b2700bcf25d1.png)

**Comment by Zalexx08** [comment]
так и остался 2016 год

**Comment by o-bender** [comment]
Часть писем Лукшин отправляет. О тоже должен у себя поправить.
