### ISSUE TITLE
фильтр

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#109]
Не все путевки попадают в список
Например, в фильтре выбрала Краснодарский край и период с 04.09 по 18.09. Путевка "Заезд с 13.09.2018 по 20.09.2018 на 8 дней" не попала в список, хотя должна была

**Comment by o-bender** [comment]
Путёвка какого санатория?

**Comment by Svetlana12** [comment]
Автотранспортник

**Comment by o-bender** [comment]
Это с Сергеем обсуди, это он их фильтрует.
