### ISSUE TITLE
мои бронирования

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#115]
Зарегистрировалась с помощью быстрой регистрации. 
По ссылке из письма для подтверждения почты не проходила. 
Оформила заказ. На странице завершения заказа нажала Мои бронирования. Появилось сообщение, что нужно подтвердить почту. 
Прошла по ссылке из письма, появилось сообщение, что регистрация прошла успешно.
Выбрала меню Мои бронирования - выдается сообщение "Внутренняя ошибка сервера"

**Comment by o-bender** [comment]
Напиши логин и пароль.
