### ISSUE TITLE
оформление бронирования - завершение

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#125]
Если у пользователя есть скидка, то на странице "Оформление бронирования-завершение" дублируется % скидки и сумма к оплате с учетом скидки. 

Сейчас сумма с учетом скидки на этой странице указывается не правильно.

**Comment by o-bender** [comment]
Скриншот в студию)

**Comment by Svetlana12** [comment]
![image](https://user-images.githubusercontent.com/38527199/45496578-731f6600-b77e-11e8-9331-f3a71802fb09.png)
