### ISSUE TITLE
Вопрос с сайта

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga3.1#137]
В письме с вопросом с сайта не указывается имя отправителя, хотя я его вводил. Причем, если указать номер телефона, то имя отправителя в письме указывается.
Письмо отправлял из раздела "Ответы на вопросы" -> "Остались вопросы?"
![default](https://user-images.githubusercontent.com/38527203/45815507-8cc22f80-bce1-11e8-8af6-95ca59803b2f.png)

**Comment by o-bender** [comment]
Проверь на тестовом сервере.

**Comment by Zalexx08** [comment]
на сайте https://test.russian-kurort.ru
![default](https://user-images.githubusercontent.com/38527203/45821766-ab7cf200-bcf2-11e8-97d2-edc2358569f0.png)
