### ISSUE TITLE
варианты сортировки

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#152]
Добавить еще один вид сортировки "путевкам" (используется по умолчанию).

Первоначально отели отсортированы по "путевкам": сначала следуют отели, в которые есть путевки, удовлетворяющие условиям, затем отели, у которых есть прейскурант, затем – отели, у которых отсутствует прейскурант. Внутри каждого раздела отели отсортированы по области, городу, коду (собственному названию).

**Comment by o-bender** [comment]
Это ещё в силе?
