### ISSUE TITLE
договор

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#162]
В меню "?" есть раздел "Договор", при нажатии на который открывается договор.
В документе 3 листа: 1,2-текст договора, а на 3й - пустой.
Можно убрать третий пустой лист?

**Comment by o-bender** [comment]
Само собой. Скачиваешь договор. Открываешь его. Нажимаешь "Печать" выбираешь doPdf принтер. Выбираешь печатать нужные листы. Печатаешь-Сохраняешь документ. Открываешь админку загружаешь новый договор. :)
