### ISSUE TITLE
Проверить туры "Как забронировать" и "Как оплатить"

### ISSUE THREAD

**Issue by o-bender** [o-bender/raduga3.1#178]

**Comment by Svetlana12** [comment]
в туре "Как забронировать" на этапе "5/6 Бронирование" нужно исправить опечатку "Тип оплаты..... **спомощью**"

**Comment by Svetlana12** [comment]
Как забронировать:
- если нажать на "Забронировать" или "Оформить", то тур закрывается и переходит на страницу "Оформление бронирования/заказа"

**Comment by Svetlana12** [comment]
Как оплатить:

- [ ] Если нажать "Оплатить картой", то выдается сообщение "Ошибка оплаты. Для продолжения необходимо авторизоваться"
