### ISSUE TITLE
Мои бронирования

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#18]
Тестовый сайт - Как оплатить:

- В самом начале тура Мои бронирования думаю нужно либо сделать неактивной кнопку Список путевок или окошко с сопровождающим текстом перенести вправо

- Сделать неактивными кнопки "Возврат оплаты", "Указать платеж", "Отказ от заказа"

![image](https://user-images.githubusercontent.com/38527199/38990902-a239cfce-43e4-11e8-8068-5f7a46b79e1d.png)

**Comment by o-bender** [comment]
А зачем?
> Сделать неактивными кнопки "Список путевок", "Возврат оплаты", "Указать платеж", "Отказ от заказа"

**Comment by Svetlana12** [comment]
Если нажать на "Возврат оплаты" или "Указать платеж" - открываются соответствующие окошки. В них можно вводить текст и нажать отправить

**Comment by Svetlana12** [comment]
А кнопка "Отказ от заказа" вызывает окно "Вы уверены, что хотите отменить заказ?"
![image](https://user-images.githubusercontent.com/38527199/39034754-39ff351a-4480-11e8-8398-d243a74b8825.png)

**Comment by o-bender** [comment]
Ну да, но ничего при этом не произойдёт. :) Зато клиент сможет потыкать кнопочки. А если они будут не рабочими, то это будет вызывать диссонанс. Не согласна?

**Comment by o-bender** [comment]
Об этом я не думал :) Хорошо, сделаю не активными.
