### ISSUE TITLE
Подтверждение бронирования

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#181]
Если при бронировании путевки был выбран вариант оплаты по счету, то пользователю не приходит письмо "Подтверждение бронирования+счет".

**Comment by Svetlana12** [comment]
Все равно не приходит письмо с подтверждением
Если выбрать оплату картой - приходит письмо, если по счету - нет

**Comment by o-bender** [comment]
а я говорю работает:)
