### ISSUE TITLE
Курорты России

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga3.1#54]
Если нажать на ссылку "Курорты России" на главной странице, то просто перебрасывает на начало страницы

![default](https://user-images.githubusercontent.com/38527203/44329307-cbf42b00-a46c-11e8-96d4-6ee09ba80a6d.png)

**Comment by o-bender** [comment]
А куда должно перебрасывать?

**Comment by Zalexx08** [comment]
можно сделать, чтобы никуда не перебрасывало? а то нажал случайно, перекинуло, крутишь опять вниз.
