### ISSUE TITLE
Оформление заявки, сроки путевки

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga3.1#58]
Если нажать на "Оформить" заявку и на следующей странице поменять приезд или отъезд, то под кнопкой "Отправить" выходит сообщение "что то пошло не так"
![default](https://user-images.githubusercontent.com/38527203/44335894-79236f00-a47e-11e8-964d-3e44e2b0678e.png)

**Comment by o-bender** [comment]
Какой санаторий и даты?

**Comment by Zalexx08** [comment]
![default](https://user-images.githubusercontent.com/38527203/44337001-de2c9400-a481-11e8-8540-118e98763a40.png)

**Comment by Zalexx08** [comment]
ошибка осталась. если меняю даты или тип номера.
![default](https://user-images.githubusercontent.com/38527203/44344903-746cb400-a49a-11e8-9b7a-b98f2277adea.png)
