### ISSUE TITLE
Посмотреть категории и цены

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga3.1#61]
У санатория Пушкино нет ссылки "Посмотреть категории и цены". В поиске указывал Пушкино с 22 по 28 августа.
![default](https://user-images.githubusercontent.com/38527203/44342716-8ea39380-a494-11e8-8c16-cb1f65538875.png)

**Comment by o-bender** [comment]
Are you sure?
![opera _2018-08-21_174138_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/44408696-8d906600-a569-11e8-91f7-b7a68b89663b.png)

**Comment by Zalexx08** [comment]
да, если объект один в списке, то нормально. Я уточнил, что в списке должно быть несколько объектов. Например, искать не санаторий Пушкино, а город Пушкино
