### ISSUE TITLE
Показать категории и цены

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#79]
При выборе меню "Показать категории и цены"в список добавляются псевдо-путевки, **даты приезда и отъезда всех заездов дублируют даты, указанные в фильтре**

**Comment by o-bender** [comment]
![opera _2018-08-28_163137_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/44726174-dc954880-aadf-11e8-86dd-6a75080205c4.png)
А тут значит оставить 1 день?

**Comment by Svetlana12** [comment]
Судя по описанию, у заявок должны указываться даты из фильтра

**Comment by o-bender** [comment]
Я про количество дней: за 1 день на 1 чел.
Оставить 1 день?

**Comment by Svetlana12** [comment]
В ТЗ не указано ничего про это поле, думаю должно указываться кол-во дней заезда, но лучше уточним у Л.Н.

**Comment by Svetlana12** [comment]
Нужно еще Стоимость изменять в зависимости от количества дней
