### ISSUE TITLE
Страница "Оформление бронирования"

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga3.1#84]
Судя по ТЗ, страница "Оформление бронирования" должна быть другой
![default](https://user-images.githubusercontent.com/38527203/44530648-99119780-a6f7-11e8-97f6-c15222f49a6a.png)

Раздел оплаты в правой части экрана содержит выбор способа оплаты – "Оплатить картой" или "Получить счет" (сначала отмечено "Оплатить картой"). Кроме того, пользователь должен поставить отметку "С условиями договора согласен" (сначала отметка не установлена). Выбор меню “Оплатить” – переход на страницу "Оформление бронирования - завершение". Если не все данные туриста указаны, то незаполненное поле выделяется, всплывает подсказка "Пожалуйста, заполните это поле" (в поле "Возраст" тот же текст!) и действие не выполняется. Если не отмечено согласие с условиями договора, то всплывает подсказка "Пожалуйста, прочитайте и установите в поле флаг", и действие не выполняется. Если пользователь не авторизован, то  выделяется поле "Электронная почта", всплывает подсказка "Пожалуйста, авторизуйтесь" и действие не выполняется.  Выбор меню "Отказаться" – закрывает окно, возвращается в "Список путевок", в котором сохраняются все предыдущие отметки.

**Comment by o-bender** [comment]
Я просто оставлю это здесь.
![opera _2018-09-03_173523_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/44992403-c71c9480-af9f-11e8-8dff-36635327e7c3.png)

**Comment by o-bender** [comment]
![opera _2018-09-04_100334_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/45015260-d0524380-b029-11e8-9a9a-123cca7dfdcf.png)

**Comment by Zalexx08** [comment]
чтобы не уходить сильно от описания этой страницы в ТЗ можно сделать две кнопки, которые турист должен выделить и потом уже нажать кнопку "Оплатить" или "Отказаться". Например, как при оформлении заказа на сайте https://madrobots.ru
 
 
![default](https://user-images.githubusercontent.com/38527203/45203600-59b18200-b285-11e8-8945-2a860cbf1c04.png)
 
 
![default](https://user-images.githubusercontent.com/38527203/45203670-8d8ca780-b285-11e8-8573-3fe8c3566ebe.png)

**Comment by o-bender** [comment]
![opera _2018-09-07_122741_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/45210886-73f55b00-b299-11e8-8fe0-977eeb62150c.png)

**Comment by o-bender** [comment]
![opera _2018-09-07_131335_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/45213314-e0735880-b29f-11e8-9149-a876ec5cdb3a.png)
![opera _2018-09-07_131249_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/45213315-e0735880-b29f-11e8-90a1-22ab7f234e05.png)
![opera _2018-09-07_131232_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/45213316-e0735880-b29f-11e8-97e3-7dc80d634143.png)

**Comment by o-bender** [comment]
![opera _2018-09-07_163738_test russian-kurort ru](https://user-images.githubusercontent.com/6534704/45222175-63a2a780-b2bc-11e8-9a75-bb292a5f4e21.png)

**Comment by Zalexx08** [comment]
1. при бронировании путевок с моментальным подтверждением должен быть изначально выбран вариант оплаты картой. Вместо "Забронировать" должно быть "Оплатить".
 
 2. строка "С условиями договора согласен" должна быть ниже кнопок с выбором варианта оплаты.
 
3. при оформлении заявки кнопок выбора способа оплаты не должно быть, только кнопки "Отправить заказ" и "Отказаться".

**Comment by Zalexx08** [comment]
по тексту из первого сообщения остался не реализованным один пункт:
"Если пользователь не авторизован, то выделяется поле "Электронная почта", всплывает подсказка "Пожалуйста, авторизуйтесь" и действие не выполняется. "
Сейчас выдается сообщение - "Пожалуйста, заполните это поле"

![default](https://user-images.githubusercontent.com/38527203/45471576-33368f80-b73a-11e8-96de-f212f8e32bea.png)
