### ISSUE TITLE
! Блок ?

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#85]
1) В блок "?" после раздела "Все отели" добавить:
	"Договор" – переход на страницу "Договор", на которой предоставляется оферта о продаже путевок в формате pdf. Вносится на сайт через программу администрирования сайта. (В меню "Личный кабинет" удалить раздел "Договор").
	"Политика конфиденциальности" – политика компании по защите персональной информации.
	"Пользовательское соглашение" – информация об алгоритме работы.
2) раздел "Нужна помощь?" переименовать в "Ответы на вопросы" и перенести после раздела "Контакты"
3) раздел ""Напишите нам" переименовать в "Нужна помощь?"

![image](https://user-images.githubusercontent.com/38527199/44531980-b85df400-a6fa-11e8-9233-124eefd0f177.png)

**Comment by o-bender** [comment]
> "Пользовательское соглашение" – информация об алгоритме работы.

Что за зверь?

**Comment by Svetlana12** [comment]
А можно перенести разделы Договор, Политика конфиденциальности, Пользовательское соглашение выше, между разделами Все отели и Новости?
