### ISSUE TITLE
! текстовый блок на странице О компании

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#88]
- второй абзац: текст "выкуплены квоты мест" выделить жирным
- третий абзац: слово "Система" заменить на "Сервис"; текст "Система интернет-бронирования "Радуга" сделать НЕ жирным;
- четвертый абзац: заменить "В системе" на "В сервисе"; 
- пятый абзац: заменить "В каталоге системы" на "В каталоге сервиса"
- седьмой абзац: заменить "через систему" на "через сервис"
- восьмой абзац: заменить "в системе" на "в сервисе"
- девятый абзац: звездочки окрасить цветом основного текста

**Comment by o-bender** [comment]
Всё это делается через админку: [О компании](https://raduga.russian-kurort.ru/aboutus)
