### ISSUE TITLE
! Вход - Забыл пароль

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga3.1#92]
Личный кабинет Войти и сэкономить - закладка Вход:
Если нажать "Забыли пароль?", то открывается новое окно, в котором вводится почта для получения пароля.
1) После поля "Электронная почта" ниже должен быть указан текст "Пароль будет отправлен по электронной почте".
2) Название кнопки "Сбросить пароль" изменить на "Отправить пароль".
3) Судя по ТЗ должна быть проверка, что в поле "Электронная почта" при восстановлении пароля указан логин (почта), зарегистрированный в сервисе.
4) ЛН считает, что при нажатии "Забыли пароль?" электронная почта должна оставаться заполненной

**Comment by o-bender** [comment]
> Судя по ТЗ должна быть проверка, что в поле "Электронная почта" при восстановлении пароля указан логин (почта), зарегистрированный в сервисе.

Проверка само собой есть, но пользователю результат этой проверки показывать не правильно. Т.к. это открывает способ подбора зарегистрированных email-ов. А затем и паролей.

> ЛН считает, что при нажатии "Забыли пароль?" электронная почта должна оставаться заполненной

Это разные поля. Так что не факт, что стоит это делать. Я подумаю в общем.
